openapi: 3.0.0
info:
  title: HCMUT Student Smart Printing Service API
  version: 1.0.0
  description: API for managing the HCMUT Student Smart Printing Service, allowing students to print documents and administrators to manage printers and system configurations.
servers:
  - url: http://localhost:3001/api
    description: Local development server


paths:
  /auth/signup:
    post:
      summary: User signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - username
                - password
              properties:
                email:
                  type: string
                  example: "bao3@123"
                username:
                  type: string
                  example: "bao3"
                password:
                  type: string
                  example: "123"
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 201
                  message:
                    type: string
                    example: "User created successfully"
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 3
                          username:
                            type: string
                            example: "bao3"
                          avatarurl:
                            type: string
                            example: "https://avatar.iran.liara.run/username?username=bao3"
                          email:
                            type: string
                            example: "bao3@123"
                          password:
                            type: string
                            description: "Hashed password"
                            example: "$2b$10$mz7EIIWJkpUsX5WKPPk7JepBanoWCBdPQi7Kc0YQvo0lyFKv3C4Qe"
                          isadmin:
                            type: boolean
                            example: false
                          createdat:
                            type: string
                            format: date-time
                            example: "2024-10-11T00:24:59.660Z"
        400:
          description: Bad request

  /auth/signin:
    post:
      summary: User signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: "bao1@123"
                password:
                  type: string
                  example: "123"
      responses:
        200:
          description: User signed in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "User signed in successfully"
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      username:
                        type: string
                        example: "bao1"
                      avatarurl:
                        type: string
                        example: "https://avatar.iran.liara.run/username?username=bao1"
                      email:
                        type: string
                        example: "bao1@123"
                      isadmin:
                        type: boolean
                        example: false
                      createdat:
                        type: string
                        format: date-time
                        example: "2024-10-09T00:45:13.342Z"
        401:
          description: Unauthorized
        400:
          description: Bad request

components:
  securitySchemes:
    HCMUT_SSO:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - HCMUT_SSO: []